### ISSUE TITLE
FLash with R 3.5.x

### ISSUE THREAD

**Issue by marchtaylor** [flr/FLash#7]
I'm having some difficulties compiling FLash with R 3.5.1. Is this a known issue?

**Comment by iagomosqueira** [comment]
Is this in Windows? What is the error? I have compiled it successfully in Windows 7, R 3.5.1, both 64 and 32 bits

**Comment by iagomosqueira** [comment]
FLash is now setup for R 64 bit. It should compile also in 32 bit, but I will revisit it. Can you try on 64 bit? Same for FLBRP and FLXSA, they are all working on 64 bit now.

**Comment by marchtaylor** [comment]
I am recompiling all of my old packages with their updated versions - this might have been the issue. It's taking a while, so I will get back to you and let you know how it goes. Thanks for your help.

**Comment by marchtaylor** [comment]
All is fine now - I am able to compile and run in R 3.5.1., 64-bit. Sorry for the false warning. There were indeed packages that hadn't correctly updated once I moved to the new R version. Also, great that FLash is working in 64-bit now - I wasn't aware of that. Cheers, Marc

**Comment by iagomosqueira** [comment]
Maybe we did not make it clear enough when releasing it.
