### ISSUE TITLE
FLash bug

### ISSUE THREAD

**Issue by clordan** [flr/FLash#9]
I have come across a strange bug when using FLash to do a medium term forecast.
This is reproduced with the ple4 example below.

library(FLCore)
library(FLash)
library(ggplotFL)

data(ple4)

ple_mtf <- stf(ple4, nyears = 10)
ple_sr <- fmle(as.FLSR(ple4, model="bevholt"), control=list(trace=0))

## first with f target
ctrl_target <- data.frame(year = 2018:2027,
                          quantity = "f",
                          val = 0.2)

ctrl_f <- fwdControl(ctrl_target)
ple_f_0.2 <- fwd(ple_mtf, ctrl = ctrl_f, sr = ple_sr)
plot(window(ple_f_0.2, start=2000))

### now with ssb target
ctrl_ssb <- fwdControl(data.frame(year=2027, quantity = "ssb", val=1000000))
ple_ssb <- fwd(ple_mtf, ctrl_ssb, sr = ple_sr)
plot(window(ple_ssb, start=2000))
# doesnt work

### now try f target afgain (exactly like before)
ple_f_0.2 <- fwd(ple_mtf, ctrl = ctrl_f, sr = ple_sr)
plot(window(ple_f_0.2, start=2000))
# doesnt work anymore either.

**Comment by iagomosqueira** [comment]
The SSB projection is giving a target only in 2027, so

```
ctrl_ssb <- fwdControl(data.frame(year=2027, quantity = "ssb", val=1000000))
```
should be

```
ctrl_ssb <- fwdControl(data.frame(year=2018:2027, quantity = "ssb", val=1000000))
```

For the second issue I am quite puzzled, will investigate further.

**Comment by iagomosqueira** [comment]
For the record, FLasher does not seem to have this problem. Please notice the difference in syntax when constructing the fwdControl, and the fact that the target to use here is 'ssb_end'.  As harvest/m.spwn is 0, there is no time to apply any F before spawning on that year, so we target the SSB at the end. FLash works by giving you the target the following year. In FLasher that can be done using 'ssb_flash'.

```
library(FLasher)
library(ggplotFL)

data(ple4)

ple_mtf <- stf(ple4, nyears = 10)
ple_sr <- fmle(as.FLSR(ple4, model="bevholt"), control=list(trace=0))

ctrl_f <- fwdControl(year = 2018:2027, quant = "f", value = 0.2)
ple_f_0.2 <- fwd(ple_mtf, control = ctrl_f, sr = ple_sr)
plot(window(ple_f_0.2, start=2000))

ctrl_ssb <- fwdControl(year=2018:2027, quant = "ssb_end", value=1000000)
ple_ssb <- fwd(ple_mtf, control=ctrl_ssb, sr = ple_sr)
plot(window(ple_ssb, start=2000))

ctrl_f <- fwdControl(year = 2018:2027, quant = "f", value = 0.2)
ple_f_0.2 <- fwd(ple_mtf, control = ctrl_f, sr = ple_sr)
plot(window(ple_f_0.2, start=2000))
```

**Comment by iagomosqueira** [comment]
When I run it with the corrected SSB control, it all seems to run. Could you please confirm?

```
library(FLCore)
library(FLash)
library(ggplotFL)

data(ple4)

ple_mtf <- stf(ple4, nyears = 10)
ple_sr <- fmle(as.FLSR(ple4, model="bevholt"), control=list(trace=0))

ctrl_target <- data.frame(year = 2017:2027,
quantity = "f",
val = 0.2)

ctrl_f <- fwdControl(ctrl_target)
ple_f_0.2 <- fwd(ple_mtf, ctrl = ctrl_f, sr = ple_sr)
plot(window(ple_f_0.2, start=2000))

ctrl_ssb <- fwdControl(data.frame(year=2018:2027, quantity = "ssb", val=1000000))
ple_ssb <- fwd(ple_mtf, ctrl_ssb, sr = ple_sr)
plot(window(ple_ssb, start=2000))

ple_f_0.2 <- fwd(ple_mtf, ctrl = ctrl_f, sr = ple_sr)
plot(window(ple_f_0.2, start=2000))
```

**Comment by clordan** [comment]
Hi Iago, yes this works for me now many thanks for the help. Colm

**Comment by iagomosqueira** [comment]
Thanks for reporting it. It is still mysterious to me why a failure makes the next one fail too. I can only think on some memory issue. FLash was written before the availability of the newer tools to code C++ with R.
